version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.4.0
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Setup Dependencies
          command: yarn install
      - run:
          name: test
          command: yarn test -- -u
